services:
  # on the rpi, we totally ignore the monitoring app mongo-express, we dont need it there to debug since its our prod env
  mongodb:
    image: apcheamitru/arm32v7-mongo:latest
  mongo-express: !reset
