name: CI - Builds & Starts the microservice

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # To be able to execute the jobs manually
  workflow_dispatch:
jobs:

  deploy:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main
        clean: true
        fetch-depth: 0

    - name: Stop and remove old container
      run: |
        docker rm -f sensors_app_prod || true

    - name: Remove old image
      run: |
        docker rmi -f sensor-microservice-sensors_app_prod || true

    - name: Build the Docker image
      run: chmod +x service-runner.sh && ./service-runner.sh
